// Import Firebase modules
import { initializeApp } from 'firebase/app';
import { getFirestore, collection, addDoc } from 'firebase/firestore';

// Import your Firebase project configuration
const firebaseConfig = {
  apiKey: "AIzaSyBJ9lZpcoG-lvO0YmVn-w0mXXzV3L4W5Kw",
  authDomain: "tendor-climbing.firebaseapp.com",
  projectId: "tendor-climbing",
  storageBucket: "tendor-climbing.appspot.com",
  messagingSenderId: "77241245133",
  appId: "1:77241245133:web:cd3ec23860f5b81fcc7884",
  measurementId: "G-LJSSSLT5RJ"
}; // Replace with your actual Firebase configuration file

// Initialize Firebase app
const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

// Array of user objects
const users = [
  {
    name: 'Charlotte Davis',
    email: 'charlotte@example.com',
    birthday: '1996-07-02',
    location: 'Vienna',
    climbingDifficultyBouldering: '7c+ to 8a',
    climbingDifficultySport: '8b+ to 9a',
    interests: 'Bouldering, Reading, Yoga, Swimming',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 13, option: 'Food/Drinks' }],
    equipmentOptions: [
      { id: 11, option: 'Climbing harness' },
      { id: 13, option: 'Quickdraws' },
      { id: 15, option: 'Carabiners' },
    ],
  },
  {
    name: 'John Smith',
    email: 'john@example.com',
    birthday: '1990-03-15',
    location: 'Salzburg',
    climbingDifficultyBouldering: '6a to 6b',
    climbingDifficultySport: '7a+ to 7c',
    interests: 'Rock climbing, Hiking, Photography',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 12, option: 'Ridesharing' }],
    equipmentOptions: [
      { id: 11, option: 'Climbing harness' },
      { id: 14, option: 'Belay device' },
      { id: 15, option: 'Carabiners' },
    ],
  },
  {
    name: 'Emma Johnson',
    email: 'emma@example.com',
    birthday: '1988-12-20',
    location: 'Graz',
    climbingDifficultyBouldering: '4 to 5+',
    climbingDifficultySport: '6c+ to 7a',
    interests: 'Indoor climbing, Yoga, Traveling',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 11, option: 'Teaching' }],
    equipmentOptions: [
      { id: 11, option: 'Climbing harness' },
      { id: 12, option: 'Climbing rope' },
    ],
  },
  {
    name: 'Oliver Wilson',
    email: 'oliver@example.com',
    birthday: '1992-05-09',
    location: 'Linz',
    climbingDifficultyBouldering: '6c+ to 7a',
    climbingDifficultySport: '7a+ to 7c',
    interests: 'Outdoor climbing, Mountain biking, Camping',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 14, option: 'Fun' }],
    equipmentOptions: [
      { id: 12, option: 'Climbing rope' },
      { id: 13, option: 'Quickdraws' },
      { id: 15, option: 'Carabiners' },
    ],
  },
  {
    name: 'Sophia Martinez',
    email: 'sophia@example.com',
    birthday: '1995-09-12',
    location: 'Innsbruck',
    climbingDifficultyBouldering: '8b+ to 9a',
    climbingDifficultySport: '7c+ to 8a',
    interests: 'Lead climbing, CrossFit, Skiing',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 13, option: 'Food/Drinks' }, { id: 11, option: 'Teaching' }],
    equipmentOptions: [
      { id: 11, option: 'Climbing harness' },
      { id: 12, option: 'Climbing rope' },
      { id: 13, option: 'Quickdraws' },
      { id: 14, option: 'Belay device' },
      { id: 15, option: 'Carabiners' },
    ],
  },
  {
    name: 'Liam Anderson',
    email: 'liam@example.com',
    birthday: '1998-02-25',
    location: 'Vienna',
    climbingDifficultyBouldering: '6a to 6b',
    climbingDifficultySport: '7a+ to 7c',
    interests: 'Bouldering, Yoga, Music',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 12, option: 'Ridesharing' }, { id: 14, option: 'Fun' }],
    equipmentOptions: [
      { id: 11, option: 'Climbing harness' },
      { id: 13, option: 'Quickdraws' },
      { id: 15, option: 'Carabiners' },
    ],
  },
  {
    name: 'Mia Taylor',
    email: 'mia@example.com',
    birthday: '1994-11-08',
    location: 'Salzburg',
    climbingDifficultyBouldering: '7c+ to 8a',
    climbingDifficultySport: '8b+ to 9a',
    interests: 'Sport climbing, Hiking, Traveling',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 13, option: 'Food/Drinks' }, { id: 11, option: 'Teaching' }],
    equipmentOptions: [
      { id: 12, option: 'Climbing rope' },
      { id: 14, option: 'Belay device' },
      { id: 15, option: 'Carabiners' },
    ],
  },
  {
    name: 'Noah Baker',
    email: 'noah@example.com',
    birthday: '1997-06-17',
    location: 'Graz',
    climbingDifficultyBouldering: '6c+ to 7a',
    climbingDifficultySport: '7a+ to 7c',
    interests: 'Indoor climbing, Yoga, Photography',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 12, option: 'Ridesharing' }, { id: 14, option: 'Fun' }],
    equipmentOptions: [
      { id: 11, option: 'Climbing harness' },
      { id: 12, option: 'Climbing rope' },
      { id: 13, option: 'Quickdraws' },
    ],
  },
  {
    name: 'Emily Wilson',
    email: 'emily@example.com',
    birthday: '1993-09-28',
    location: 'Vienna',
    climbingDifficultyBouldering: '7c+ to 8a',
    climbingDifficultySport: '8b+ to 9a',
    interests: 'Bouldering, Yoga, Music',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 13, option: 'Food/Drinks' }, { id: 14, option: 'Fun' }],
    equipmentOptions: [
      { id: 11, option: 'Climbing harness' },
      { id: 12, option: 'Climbing rope' },
      { id: 14, option: 'Belay device' },
      { id: 15, option: 'Carabiners' },
    ],
  },
  {
    name: 'William Thompson',
    email: 'william@example.com',
    birthday: '1991-05-03',
    location: 'Salzburg',
    climbingDifficultyBouldering: '6a to 6b',
    climbingDifficultySport: '7a+ to 7c',
    interests: 'Rock climbing, Hiking, Traveling',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 11, option: 'Teaching' }],
    equipmentOptions: [
      { id: 11, option: 'Climbing harness' },
      { id: 13, option: 'Quickdraws' },
      { id: 15, option: 'Carabiners' },
    ],
  },
  {
    name: 'Sophie Anderson',
    email: 'sophie@example.com',
    birthday: '1987-12-17',
    location: 'Graz',
    climbingDifficultyBouldering: '4 to 5+',
    climbingDifficultySport: '6c+ to 7a',
    interests: 'Indoor climbing, Yoga, Photography',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 12, option: 'Ridesharing' }],
    equipmentOptions: [
      { id: 11, option: 'Climbing harness' },
      { id: 12, option: 'Climbing rope' },
    ],
  },
  {
    name: 'Olivia Brown',
    email: 'olivia@example.com',
    birthday: '1994-08-11',
    location: 'Linz',
    climbingDifficultyBouldering: '6c+ to 7a',
    climbingDifficultySport: '7a+ to 7c',
    interests: 'Outdoor climbing, Mountain biking, Camping',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 14, option: 'Fun' }],
    equipmentOptions: [
      { id: 12, option: 'Climbing rope' },
      { id: 13, option: 'Quickdraws' },
      { id: 15, option: 'Carabiners' },
    ],
  },
  {
    name: 'Lucas Davis',
    email: 'lucas@example.com',
    birthday: '1990-02-19',
    location: 'Innsbruck',
    climbingDifficultyBouldering: '8b+ to 9a',
    climbingDifficultySport: '7c+ to 8a',
    interests: 'Lead climbing, CrossFit, Skiing',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 13, option: 'Food/Drinks' }, { id: 11, option: 'Teaching' }],
    equipmentOptions: [
      { id: 11, option: 'Climbing harness' },
      { id: 12, option: 'Climbing rope' },
      { id: 13, option: 'Quickdraws' },
      { id: 14, option: 'Belay device' },
      { id: 15, option: 'Carabiners' },
    ],
  },
  {
    name: 'Alexander Martinez',
    email: 'alexander@example.com',
    birthday: '1993-11-30',
    location: 'Vienna',
    climbingDifficultyBouldering: '6a to 6b',
    climbingDifficultySport: '7a+ to 7c',
    interests: 'Bouldering, Yoga, Music',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 12, option: 'Ridesharing' }, { id: 14, option: 'Fun' }],
    equipmentOptions: [
      { id: 11, option: 'Climbing harness' },
      { id: 13, option: 'Quickdraws' },
      { id: 15, option: 'Carabiners' },
    ],
  },
  {
    name: 'Ella Taylor',
    email: 'ella@example.com',
    birthday: '1997-01-14',
    location: 'Salzburg',
    climbingDifficultyBouldering: '7c+ to 8a',
    climbingDifficultySport: '8b+ to 9a',
    interests: 'Sport climbing, Hiking, Traveling',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 13, option: 'Food/Drinks' }, { id: 11, option: 'Teaching' }],
    equipmentOptions: [
      { id: 12, option: 'Climbing rope' },
      { id: 14, option: 'Belay device' },
      { id: 15, option: 'Carabiners' },
    ],
  },
  {
    name: 'James Wilson',
    email: 'james@example.com',
    birthday: '1992-07-08',
    location: 'Graz',
    climbingDifficultyBouldering: '6c+ to 7a',
    climbingDifficultySport: '7a+ to 7c',
    interests: 'Indoor climbing, Yoga, Photography',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 12, option: 'Ridesharing' }, { id: 14, option: 'Fun' }],
    equipmentOptions: [
      { id: 11, option: 'Climbing harness' },
      { id: 12, option: 'Climbing rope' },
      { id: 13, option: 'Quickdraws' },
    ],
  },
  {
    name: 'Grace Baker',
    email: 'grace@example.com',
    birthday: '1995-03-23',
    location: 'Vienna',
    climbingDifficultyBouldering: '7c+ to 8a',
    climbingDifficultySport: '8b+ to 9a',
    interests: 'Bouldering, Reading, Yoga, Swimming',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 13, option: 'Food/Drinks' }],
    equipmentOptions: [
      { id: 11, option: 'Climbing harness' },
      { id: 13, option: 'Quickdraws' },
      { id: 15, option: 'Carabiners' },
    ],
  },
  {
    name: 'Benjamin Smith',
    email: 'benjamin@example.com',
    birthday: '1990-12-02',
    location: 'Salzburg',
    climbingDifficultyBouldering: '6a to 6b',
    climbingDifficultySport: '7a+ to 7c',
    interests: 'Rock climbing, Hiking, Photography',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 11, option: 'Teaching' }],
    equipmentOptions: [
      { id: 11, option: 'Climbing harness' },
      { id: 14, option: 'Belay device' },
      { id: 15, option: 'Carabiners' },
    ],
  },
  {
    name: 'Natalie Johnson',
    email: 'natalie@example.com',
    birthday: '1988-08-27',
    location: 'Graz',
    climbingDifficultyBouldering: '4 to 5+',
    climbingDifficultySport: '6c+ to 7a',
    interests: 'Indoor climbing, Yoga, Traveling',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 11, option: 'Teaching' }],
    equipmentOptions: [
      { id: 11, option: 'Climbing harness' },
      { id: 12, option: 'Climbing rope' },
    ],
  },
  {
    name: 'Daniel Anderson',
    email: 'daniel@example.com',
    birthday: '1992-03-05',
    location: 'Linz',
    climbingDifficultyBouldering: '6c+ to 7a',
    climbingDifficultySport: '7a+ to 7c',
    interests: 'Outdoor climbing, Mountain biking, Camping',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 14, option: 'Fun' }],
    equipmentOptions: [
      { id: 12, option: 'Climbing rope' },
      { id: 13, option: 'Quickdraws' },
      { id: 15, option: 'Carabiners' },
    ],
  },
  {
    name: 'Ava Davis',
    email: 'ava@example.com',
    birthday: '1995-10-18',
    location: 'Innsbruck',
    climbingDifficultyBouldering: '8b+ to 9a',
    climbingDifficultySport: '7c+ to 8a',
    interests: 'Lead climbing, CrossFit, Skiing',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 13, option: 'Food/Drinks' }, { id: 11, option: 'Teaching' }],
    equipmentOptions: [
      { id: 11, option: 'Climbing harness' },
      { id: 12, option: 'Climbing rope' },
      { id: 13, option: 'Quickdraws' },
      { id: 14, option: 'Belay device' },
      { id: 15, option: 'Carabiners' },
    ],
  },
  {
    name: 'Joseph Martinez',
    email: 'joseph@example.com',
    birthday: '1998-01-09',
    location: 'Vienna',
    climbingDifficultyBouldering: '6a to 6b',
    climbingDifficultySport: '7a+ to 7c',
    interests: 'Bouldering, Yoga, Music',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 12, option: 'Ridesharing' }, { id: 14, option: 'Fun' }],
    equipmentOptions: [
      { id: 11, option: 'Climbing harness' },
      { id: 13, option: 'Quickdraws' },
      { id: 15, option: 'Carabiners' },
    ],
  },
  {
    name: 'Chloe Taylor',
    email: 'chloe@example.com',
    birthday: '1994-06-07',
    location: 'Salzburg',
    climbingDifficultyBouldering: '7c+ to 8a',
    climbingDifficultySport: '8b+ to 9a',
    interests: 'Sport climbing, Hiking, Traveling',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 13, option: 'Food/Drinks' }, { id: 11, option: 'Teaching' }],
    equipmentOptions: [
      { id: 12, option: 'Climbing rope' },
      { id: 14, option: 'Belay device' },
      { id: 15, option: 'Carabiners' },
    ],
  },
  {
    name: 'Samuel Baker',
    email: 'samuel@example.com',
    birthday: '1997-02-16',
    location: 'Graz',
    climbingDifficultyBouldering: '6c+ to 7a',
    climbingDifficultySport: '7a+ to 7c',
    interests: 'Indoor climbing, Yoga, Photography',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 12, option: 'Ridesharing' }, { id: 14, option: 'Fun' }],
    equipmentOptions: [
      { id: 11, option: 'Climbing harness' },
      { id: 12, option: 'Climbing rope' },
      { id: 13, option: 'Quickdraws' },
    ],
  },
  {
    name: 'Sophie Miller',
    email: 'sophie.m@example.com',
    birthday: '1991-09-05',
    location: 'Innsbruck',
    climbingDifficultyBouldering: '8a to 8b+',
    climbingDifficultySport: '9a to 9b',
    interests: 'Lead climbing, Mountaineering, Skiing',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 11, option: 'Teaching' }, { id: 13, option: 'Food/Drinks' }],
    equipmentOptions: [
      { id: 11, option: 'Climbing harness' },
      { id: 12, option: 'Climbing rope' },
      { id: 13, option: 'Quickdraws' },
      { id: 14, option: 'Belay device' },
    ],
  },
  {
    name: 'Maximilian Weber',
    email: 'maximilian.w@example.com',
    birthday: '1993-11-15',
    location: 'Vienna',
    climbingDifficultyBouldering: '7b to 7c+',
    climbingDifficultySport: '8a+ to 8b+',
    interests: 'Bouldering, Yoga, Music',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 12, option: 'Ridesharing' }, { id: 14, option: 'Fun' }],
    equipmentOptions: [
      { id: 11, option: 'Climbing harness' },
      { id: 13, option: 'Quickdraws' },
      { id: 15, option: 'Carabiners' },
    ],
  },
  {
    name: 'Emilia Fischer',
    email: 'emilia.f@example.com',
    birthday: '1996-12-20',
    location: 'Salzburg',
    climbingDifficultyBouldering: '6a to 6b+',
    climbingDifficultySport: '7b to 7c+',
    interests: 'Rock climbing, Hiking, Photography',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 11, option: 'Teaching' }],
    equipmentOptions: [
      { id: 11, option: 'Climbing harness' },
      { id: 14, option: 'Belay device' },
      { id: 15, option: 'Carabiners' },
    ],
  },
  {
    name: 'David Müller',
    email: 'david.m@example.com',
    birthday: '1990-05-09',
    location: 'Graz',
    climbingDifficultyBouldering: '5 to 6a+',
    climbingDifficultySport: '6c to 7b',
    interests: 'Indoor climbing, Yoga, Traveling',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 12, option: 'Ridesharing' }],
    equipmentOptions: [
      { id: 11, option: 'Climbing harness' },
      { id: 12, option: 'Climbing rope' },
    ],
  },
  {
    name: 'Hannah Schneider',
    email: 'hannah.s@example.com',
    birthday: '1994-09-12',
    location: 'Linz',
    climbingDifficultyBouldering: '7a to 7b+',
    climbingDifficultySport: '8a to 8b+',
    interests: 'Outdoor climbing, Hiking, Camping',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 13, option: 'Food/Drinks' }],
    equipmentOptions: [
      { id: 11, option: 'Climbing harness' },
      { id: 13, option: 'Quickdraws' },
      { id: 15, option: 'Carabiners' },
    ],
  },
  {
    name: 'Julia Schneider',
    email: 'julia.s@example.com',
    birthday: '1995-06-21',
    location: 'Innsbruck',
    climbingDifficultyBouldering: '7c+ to 8a',
    climbingDifficultySport: '8b+ to 9a',
    interests: 'Lead climbing, Yoga, Skiing',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 13, option: 'Food/Drinks' }, { id: 11, option: 'Teaching' }],
    equipmentOptions: [
      { id: 11, option: 'Climbing harness' },
      { id: 12, option: 'Climbing rope' },
      { id: 13, option: 'Quickdraws' },
      { id: 14, option: 'Belay device' },
      { id: 15, option: 'Carabiners' },
    ],
  },
  // User 2
  {
    name: 'Leon Fischer',
    email: 'leon.f@example.com',
    birthday: '1992-02-14',
    location: 'Vienna',
    climbingDifficultyBouldering: '6a to 6b',
    climbingDifficultySport: '7a+ to 7c',
    interests: 'Bouldering, Music, Traveling',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 12, option: 'Ridesharing' }, { id: 14, option: 'Fun' }],
    equipmentOptions: [
      { id: 11, option: 'Climbing harness' },
      { id: 13, option: 'Quickdraws' },
      { id: 15, option: 'Carabiners' },
    ],
  },
  // User 3
  {
    name: 'Lena Weber',
    email: 'lena.w@example.com',
    birthday: '1997-10-10',
    location: 'Salzburg',
    climbingDifficultyBouldering: '4 to 5+',
    climbingDifficultySport: '6c+ to 7a',
    interests: 'Indoor climbing, Yoga, Reading',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 11, option: 'Teaching' }],
    equipmentOptions: [
      { id: 11, option: 'Climbing harness' },
      { id: 12, option: 'Climbing rope' },
    ],
  },
  // User 4
  {
    name: 'Felix Müller',
    email: 'felix.m@example.com',
    birthday: '1991-08-28',
    location: 'Graz',
    climbingDifficultyBouldering: '6c+ to 7a',
    climbingDifficultySport: '7a+ to 7c',
    interests: 'Outdoor climbing, Hiking, Camping',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 14, option: 'Fun' }],
    equipmentOptions: [
      { id: 12, option: 'Climbing rope' },
      { id: 13, option: 'Quickdraws' },
      { id: 15, option: 'Carabiners' },
    ],
  },
  // User 5
  {
    name: 'Laura Schmidt',
    email: 'laura.s@example.com',
    birthday: '1996-03-15',
    location: 'Innsbruck',
    climbingDifficultyBouldering: '8b+ to 9a',
    climbingDifficultySport: '7c+ to 8a',
    interests: 'Lead climbing, CrossFit, Skiing',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 13, option: 'Food/Drinks' }, { id: 11, option: 'Teaching' }],
    equipmentOptions: [
      { id: 11, option: 'Climbing harness' },
      { id: 12, option: 'Climbing rope' },
      { id: 13, option: 'Quickdraws' },
      { id: 14, option: 'Belay device' },
      { id: 15, option: 'Carabiners' },
    ],
  },
  // User 6
  {
    name: 'Maximilian Berger',
    email: 'maximilian.b@example.com',
    birthday: '1993-12-01',
    location: 'Vienna',
    climbingDifficultyBouldering: '6a to 6b',
    climbingDifficultySport: '7a+ to 7c',
    interests: 'Bouldering, Yoga, Music',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 12, option: 'Ridesharing' }, { id: 14, option: 'Fun' }],
    equipmentOptions: [
      { id: 11, option: 'Climbing harness' },
      { id: 13, option: 'Quickdraws' },
      { id: 15, option: 'Carabiners' },
    ],
  },
  // User 7
  {
    name: 'Hannah Müller',
    email: 'hannah.m@example.com',
    birthday: '1994-05-05',
    location: 'Salzburg',
    climbingDifficultyBouldering: '7c+ to 8a',
    climbingDifficultySport: '8b+ to 9a',
    interests: 'Sport climbing, Hiking, Traveling',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 13, option: 'Food/Drinks' }, { id: 11, option: 'Teaching' }],
    equipmentOptions: [
      { id: 12, option: 'Climbing rope' },
      { id: 14, option: 'Belay device' },
      { id: 15, option: 'Carabiners' },
    ],
  },
  // User 8
  {
    name: 'Moritz Wagner',
    email: 'moritz.w@example.com',
    birthday: '1997-11-18',
    location: 'Graz',
    climbingDifficultyBouldering: '6c+ to 7a',
    climbingDifficultySport: '7a+ to 7c',
    interests: 'Indoor climbing, Yoga, Photography',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 12, option: 'Ridesharing' }, { id: 14, option: 'Fun' }],
    equipmentOptions: [
      { id: 11, option: 'Climbing harness' },
      { id: 12, option: 'Climbing rope' },
      { id: 13, option: 'Quickdraws' },
    ],
  },
  // User 9
  {
    name: 'Isabella Schuster',
    email: 'isabella.s@example.com',
    birthday: '1993-09-30',
    location: 'Vienna',
    climbingDifficultyBouldering: '7c+ to 8a',
    climbingDifficultySport: '8b+ to 9a',
    interests: 'Bouldering, Yoga, Music',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 13, option: 'Food/Drinks' }, { id: 14, option: 'Fun' }],
    equipmentOptions: [
      { id: 11, option: 'Climbing harness' },
      { id: 12, option: 'Climbing rope' },
      { id: 14, option: 'Belay device' },
      { id: 15, option: 'Carabiners' },
    ],
  },
  // User 10
  {
    name: 'Niklas Huber',
    email: 'niklas.h@example.com',
    birthday: '1991-06-13',
    location: 'Salzburg',
    climbingDifficultyBouldering: '6a to 6b',
    climbingDifficultySport: '7a+ to 7c',
    interests: 'Rock climbing, Hiking, Traveling',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 11, option: 'Teaching' }],
    equipmentOptions: [
      { id: 11, option: 'Climbing harness' },
      { id: 13, option: 'Quickdraws' },
      { id: 15, option: 'Carabiners' },
    ],
  },
  // User 11
  {
    name: 'Lara Berger',
    email: 'lara.b@example.com',
    birthday: '1989-12-27',
    location: 'Graz',
    climbingDifficultyBouldering: '4 to 5+',
    climbingDifficultySport: '6c+ to 7a',
    interests: 'Indoor climbing, Yoga, Traveling',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 12, option: 'Ridesharing' }],
    equipmentOptions: [
      { id: 11, option: 'Climbing harness' },
      { id: 12, option: 'Climbing rope' },
    ],
  },
  // User 12
  {
    name: 'Fabian Mayer',
    email: 'fabian.m@example.com',
    birthday: '1994-07-14',
    location: 'Linz',
    climbingDifficultyBouldering: '6c+ to 7a',
    climbingDifficultySport: '7a+ to 7c',
    interests: 'Outdoor climbing, Mountain biking, Camping',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 14, option: 'Fun' }],
    equipmentOptions: [
      { id: 12, option: 'Climbing rope' },
      { id: 13, option: 'Quickdraws' },
      { id: 15, option: 'Carabiners' },
    ],
  },
  // User 13
  {
    name: 'Sophie Winter',
    email: 'sophie.w@example.com',
    birthday: '1990-05-19',
    location: 'Innsbruck',
    climbingDifficultyBouldering: '8b+ to 9a',
    climbingDifficultySport: '7c+ to 8a',
    interests: 'Lead climbing, CrossFit, Skiing',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 13, option: 'Food/Drinks' }, { id: 11, option: 'Teaching' }],
    equipmentOptions: [
      { id: 11, option: 'Climbing harness' },
      { id: 12, option: 'Climbing rope' },
      { id: 13, option: 'Quickdraws' },
      { id: 14, option: 'Belay device' },
      { id: 15, option: 'Carabiners' },
    ],
  },
  // User 14
  {
    name: 'Finn Winkler',
    email: 'finn.w@example.com',
    birthday: '1993-10-05',
    location: 'Vienna',
    climbingDifficultyBouldering: '6a to 6b',
    climbingDifficultySport: '7a+ to 7c',
    interests: 'Bouldering, Yoga, Music',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 12, option: 'Ridesharing' }, { id: 14, option: 'Fun' }],
    equipmentOptions: [
      { id: 11, option: 'Climbing harness' },
      { id: 13, option: 'Quickdraws' },
      { id: 15, option: 'Carabiners' },
    ],
  },
  // User 15
  {
    name: 'Emilia Hofmann',
    email: 'emilia.h@example.com',
    birthday: '1996-08-31',
    location: 'Salzburg',
    climbingDifficultyBouldering: '7c+ to 8a',
    climbingDifficultySport: '8b+ to 9a',
    interests: 'Sport climbing, Hiking, Traveling',
    showInDatabase: true,
    termsAccepted: true,
    profileImage: '',
    serviceOptions: [{ id: 13, option: 'Food/Drinks' }, { id: 11, option: 'Teaching' }],
    equipmentOptions: [
      { id: 12, option: 'Climbing rope' },
      { id: 14, option: 'Belay device' },
      { id: 15, option: 'Carabiners' },
    ],
  },
];
// Upload users to Firestore
async function uploadUsers() {
  for (const user of users) {
    try {
      const docRef = await addDoc(collection(db, 'users'), user);
      console.log('User added with ID:', docRef.id);
    } catch (error) {
      console.error('Error adding user:', error);
    }
  }
}

// Call the uploadUsers function
uploadUsers()
  .then(() => {
    console.log('Users uploaded successfully.');
    process.exit(0); // Exit the script
  })
  .catch((error) => {
    console.error('Error uploading users:', error);
    process.exit(1); // Exit the script with an error code
  });
